version: "3"

services:
  mongo:
    image: mongo:7.0-rc
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234qwer
    ports:
      - 37017:37017 
